### ISSUE TITLE
What does your dev environment look like? Hardware  + Software

### ISSUE THREAD

**Issue by AchoArnold** [tiborsimon/ama#2]

**Comment by tiborsimon** [comment]
I'm trying to be as machine independent as possible. My main hardware platform is OS X but actually it doesn't matter as long as I work on an unix based system. I have a [dotfiles](https://github.com/tiborsimon/dotfiles) config that I can deploy in seconds. I mainly work in the terminal. Main main editor is vim. I prefer the fast workflow taht it provides, and I miss it very much when I use an IDE (I feel crippled in them). I sometimes use PyCharm with vim keys, but it's not the same.

For notes I use Evernote. I used to use in the past Tiddly Wiki and Zim, but I missed the phone integration, and the fast photo insertion, so I sticked to Evernote.

For versioning, I use GitHub and Bitbucket, and I keep my files in Dropbox.
